const IS_USER_AUTH = "IS_USER_AUTH"
const USERS_LIST = "USERS_LIST"
const ACTIVE_USER = "ACTIVE_USER"
const INACTIVE_USER = "INACTIVE_USER"

export default{IS_USER_AUTH, USERS_LIST, INACTIVE_USER, ACTIVE_USER}